version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/TODO-Docker  # <-- important!

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: TODO-Docker
    ports:
      - "5432:5432"
